### ISSUE TITLE
no deepr

### ISSUE THREAD

**Issue by danbikle** [woobe/blenditbayes#1]
I am seeing this error:

> suppressMessages(library(deepr))
> Error in library(deepr) : there is no package called ‘deepr’
> Calls: suppressMessages -> withCallingHandlers -> library
> Execution halted
> dan@hp /m/b/e $ 

I think more documentation would be good.

Which version of R should I use?
What is the syntax I use to install the packages I need?

**Comment by woobe** [comment]
Hi there,

`deepr` isn't on CRAN yet so you need to install it using `devtools`.
R version >= 3.0.0 will do.

Try the following commands:

```
install.packages("devtools")
library(devtools)
install_github("woobe/deepr")
library(deepr)
```

For more information about `deepr`, see this (https://github.com/woobe/deepr).

Cheers,
Joe
