### ISSUE TITLE
unused argument (key = "dat")

### ISSUE THREAD

**Issue by vincentvanhees** [woobe/blenditbayes#2]
I am getting this error:

> dat_h2o <- as.h2o(localH2O, dat, key = 'dat')
> Error in as.h2o(localH2O, dat, key = "dat") : 
>   unused argument (key = "dat")

I am running your [code](https://github.com/woobe/blenditbayes/blob/master/2014-07-h2o-experiments/code_h2o_dnn_exp_1.R) with latest h2o version h2o_3.6.0.8 in R 3.2.3 (2015-12-10); Platform: x86_64-pc-linux-gnu (64-bit); Ubuntu 14.04.3 LT

thanks for sharing your code

**Comment by woobe** [comment]
Hi Vincent,

The code was written for the classic h2o quite a while ago. There have been some changes in syntax since version 3. Please have a look at this [post](http://stackoverflow.com/questions/31442820/unable-to-convert-data-frame-to-h2o-object). Hope it helps. When I have a chance, I will update my old code in all my previous blog posts.

Cheers,
Joe

**Comment by charleystran** [comment]
+1 

I am also having several issues here that seem to be because of old code. I understand that it will take some time to update but could you possible list the versions that it did work for? I am eager to try it out even on an older version

**Comment by vincentvanhees** [comment]
Joe - Thanks for the response and for the link.

Charley - if you change every occurrence of 'data = dat_h2o[row_train, ],'
to 'training_frame = dat_h2o[row_train, ],'
you should get something that at least runs and generates output. The
output does not look like the output in the blog example, but at least the
code then works.

You may want to have a look at other more up to date tutorials like this
one:
https://h2o-release.s3.amazonaws.com/h2o/rel-slater/9/docs-website/h2o-docs/booklets/DeepLearning_Vignette.pdf

Cheers, Vincent

**Comment by woobe** [comment]
Hi Charley,

Here is the [link](http://h2o-release.s3.amazonaws.com/h2o/rel-nunes/2/index.html) to the latest stable release of H2O classic. After unzipping the h2o-2.8.6.2.zip, you will find the R package tar.gz in the R folder.

Thanks Vincent for the comment :)

Cheers,
Joe

**Comment by charleystran** [comment]
Hey everyone,
Thank you for the links! I actually was experiencing slightly different errors 
`
Got exception 'class water.exceptions.H2OModelBuilderIllegalArgumentException', with msg 'Illegal argument(s) for deeplearning model: DeepLearning_model_R_1455122734680_5.  Details: ERROR on field: _balance_classes: balance_classes requires classification.
'
water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for deeplearning model: DeepLearning_model_R_1455122734680_5.  Details: ERROR on field: _balance_classes: balance_classes requires classification
`
The links provided do not use that parameter, but I am still able to use them without any errors. So for now, I am good. Thank you!
